# Generated by Django 3.1 on 2020-08-24 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=12, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('pagamento', models.BooleanField(default=True)),
                ('repeticao', models.BooleanField(default=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Escolha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeros', models.IntegerField()),
                ('sorteado', models.BooleanField(default=False)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pessoa')),
            ],
            options={
                'ordering': ['numeros'],
                'unique_together': {('pessoa', 'numeros')},
            },
        ),
    ]
