# Generated by Django 3.1 on 2020-08-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dezenas_rodadas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dezenas',
            options={'ordering': ['dezena']},
        ),
        migrations.AlterField(
            model_name='rodadas',
            name='num_rodada',
            field=models.CharField(max_length=40, verbose_name='Numero da rodada'),
        ),
        migrations.AlterUniqueTogether(
            name='dezenas',
            unique_together={('rodada', 'dezena')},
        ),
    ]
