# Generated by Django 3.1 on 2020-08-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_testes_marco'),
    ]

    operations = [
        migrations.CreateModel(
            name='TesteUm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('numero', models.IntegerField()),
            ],
        ),
    ]
