# Generated by Django 3.1 on 2020-08-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200828_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testes',
            name='marco',
            field=models.CharField(blank=True, choices=[('1', '1'), ('0', '0')], default=0, max_length=1, null=True),
        ),
    ]
