# Generated by Django 3.1 on 2020-08-29 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200828_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='escolha',
            name='acertos',
            field=models.IntegerField(default=0),
        ),
    ]
