# Generated by Django 3.1 on 2020-08-29 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_escolha_acertos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escolha',
            name='acertos',
        ),
    ]
