# Generated by Django 3.1 on 2020-08-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200828_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='escolha',
            name='quantidade',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
