# Generated by Django 3.1 on 2020-08-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_escolha_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escolha',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='quantidade',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
