# Generated by Django 3.1 on 2020-08-30 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200829_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_max_ponto', models.IntegerField()),
                ('v_min_ponto', models.IntegerField()),
                ('valor_jogada', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Testes',
        ),
        migrations.DeleteModel(
            name='TesteUm',
        ),
    ]
