# Generated by Django 3.1 on 2020-08-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200829_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='lucro',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
    ]
