# Generated by Django 3.1 on 2020-08-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200830_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodadas',
            name='num_rodada',
            field=models.CharField(choices=[('1° Rodada', '1° Rodada'), ('2° Rodada', '2° Rodada'), ('3° Rodada', '3° Rodada'), ('4° Rodada', '4° Rodada'), ('5° Rodada', '5° Rodada'), ('6° Rodada', '6° Rodada'), ('7° Rodada', '7° Rodada'), ('8° Rodada', '8° Rodada'), ('9° Rodada', '9° Rodada'), ('10° Rodada', '10° Rodada'), ('11° Rodada', '11° Rodada')], max_length=11, verbose_name='Numero da rodada'),
        ),
    ]
