# Generated by Django 3.1 on 2020-08-31 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200830_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acertos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acertos', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pessoa')),
            ],
        ),
    ]
