# Generated by Django 3.1 on 2020-09-01 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_acertos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escolha',
            options={'ordering': ['numeros'], 'verbose_name': 'Escolha', 'verbose_name_plural': 'Escolhas'},
        ),
    ]
