# Generated by Django 3.1 on 2020-10-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20201019_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='v_max_ponto',
            field=models.IntegerField(blank=True, null=True, verbose_name='Porcentagem para maior pontuador. ex(30) para 30%'),
        ),
        migrations.AlterField(
            model_name='config',
            name='v_min_ponto',
            field=models.IntegerField(blank=True, null=True, verbose_name='Porcentagem para menor pontuador. ex(10) para 10%'),
        ),
        migrations.AlterField(
            model_name='config',
            name='valor_jogada',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor padrão de cada rodada, ex: 10, para 10,00R$'),
        ),
    ]
