# Generated by Django 3.1 on 2020-10-22 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20201020_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='valor',
        ),
    ]
